packages:
  - 'apps/*'
  - 'packages/*'
catalog:
  eslint: 9.16.0
  next: 15.1.0
  prettier: 3.4.2
  turbo: 2.3.3
  typescript: 5.7.2
  '@types/node': 22.10.1
  lint-staged: 15.2.11
  '@changesets/cli': '2.27.10'
  husky: 9.1.7
catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    '@types/react': 19.0.0
    '@types/react-dom': 19.0.0
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    '@types/react': 18.3.1
    '@types/react-dom': 18.3.1
  next15:
    next: 15.1.0
  '@commitlint':
    '@commitlint/cli': 19.6.0
    '@commitlint/config-conventional': 19.6.0
